### ISSUE TITLE
path.binread doesn't work on Ruby 1.8.7

### ISSUE THREAD

**Issue by mathieulegrand** [applicationsonline/librarian-chef#3]
When running on a vanilla install of Mac OS X, IO.respond_to?(:binread) returns true but path.binread does not work. Editing manifest_reader.rb to always use path.read fixes the issue.

**Comment by twissmueller** [comment]
Same here. While doing `librarian-chef install` on a fresh CentOS 6.3 with Ruby 1.8.7 I get the following exception:

```

/usr/lib/ruby/gems/1.8/gems/librarian-0.0.26/lib/librarian/chef/manifest_reader.rb:49:in `binread': undefined method `binread' for #<Pathname:0x7f925b8dc558> (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/librarian-0.0.26/lib/librarian/chef/manifest_reader.rb:19:in `read_manifest'
```

After changing line 49 of `manifest_reader.rb` from `path.binread` to `path.read` everything worked.

**Comment by yfeldblum** [comment]
Check if this is fixed in 76cb3cbee990fced59836578bb07d2dd9411133d, which is included in v0.0.1.
